language: node_js
dist: trusty

node_js:
  - "node"

branches:
  only:
    - master

install:
  - cat ./deploy/my_known_hosts >> ~/.ssh/known_hosts
  - (echo $MY_SSH_KEY | base64 --decode -i > ~/.ssh/id_rsa)
  - chmod 600 ~/.ssh/id_rsa
  - chmod 644 ~/.ssh/known_hosts
  - npm i yarn -g
  - yarn install --production
  
script:
  - yarn build

after_success:
  - ssh -i id_rsa $SSH_CONNECTING_STRING
  - pwd
