language: node_js

node_js:
  - "node"

addons:
    apt:
        packages:
            - sshpass

branches:
  only:
    - master

install:
  - npm install --silent

script:
  - npm run build

after_success:
  - which sshpass
  - /usr/bin/sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST pwd