language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "node"

branches:
  only:
    - master

install:
  - npm i yarn -g
  - yarn

script:
  - yarn build

after_success:
  - node ./deploy/ftp.js