language: node_js

node_js:
  - "node"

branches:
  only:
    - master

install:
  - npm i pushstate-server -g
  - npm install

script:
  - npm run build
  - pushstate-server build &
  - APP_TEST_PID=$(echo $!)
  - PORT=3001 CI=true npm run test
  - kill $APP_TEST_PID

after_success:
  - node ./deploy/ftp.js