language: node_js

node_js:
  - "node"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build
  - sed -ie 's/<!--adblock-->/<script src="\/ads.js?<?php echo uniqid() ?>"><\/script>/g' ./build/index.html
  - mv ./build/index.html ./build/index.php
  - rm -f ./build/index.htmle

after_success:
  - node ./deploy/ftp.js