language: node_js
dist: trusty

node_js:
  - "node"

branches:
  only:
    - master

install:
  - cat ./deploy/my_known_hosts >> ~/.ssh/known_hosts
  - (echo $MY_SSH_KEY | base64 --decode -i > ~/.ssh/do)
  - chmod 600 ~/.ssh/do
  - chmod 644 ~/.ssh/known_hosts
  - ls ~/.ssh -al
  - npm i yarn -g
  - yarn install --production
  
script:
  - yarn build

after_success:
  - ssh -i do $SSH_CONNECTING_STRING
  - pwd
