language: node_js

node_js:
  - "node"

addons:
    apt:
        packages:
            - sshpass

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

after_success:
  - export SSHPASS=$SSH_PASSWORD
  - sshpass -e ssh $SSH_USER@$SSH_HOST pwd