language: node_js
dist: trusty
sudo: required

node_js:
  - "node"

branches:
  only:
    - master

install:
  - sudo apt install sshpass -y
  - npm install --silent

script:
  - npm run build

after_success:
  - sudo /usr/bin/sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST pwd
